import type { NextPage } from 'next'
import Head from 'next/head'
import { IProduct } from '../interface/IProduct'
import { MainContainer } from '../styles/MainStyled'
// components
import CardProduct from '../components/CardProduct'
import { CardContainer } from '../components/CardProduct/CardProductStyled'



const URL = 'https://mks-frontend-challenge-api.herokuapp.com/api/v1/products/?page=1&rows=8&sortBy=id&orderBy=ASC'

export async function getStaticProps() {

  const res = await fetch(URL);
  const { products } = await res.json();
  
  return {
    props: { products },
  }
  
}

interface ProductsProp  {
  products: IProduct[]
}

const Home: NextPage<ProductsProp> = ({ products }) => {
  return (
    <>
      <Head>
        <title>MKS Digital Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer>
        {
          products.map((product) => (
            <CardProduct key={ product.id } product={product} />
          ))
        }
      </MainContainer>
    </>
  )
}

export default Home
